Add max-width to right half of hero section
Wubbadub/ClubHub pull request #102
Opened 2016-11-22 03:17 UTC by kelseyll

Once I test it in local I will assign someone to review

2016-11-22 18:15 UTC, hwkr requested changes
We should make this work.

2016-11-22 18:15 UTC, hwkr commented on client/components/pages/editor/sections/Hero.jsx
> +        <ShortTextField maxLength="60"label="Title" onChange={this.handleChange} value={this.props.data.title} name="title"/>
I don't think this code will work. Did you test it?
(These text fields are react components so `maxLength` isn't a property. You should pass it down into the components as props and apply it to the internal `<inputs>`).

2016-11-22 20:39 UTC, kelseyll commented on client/components/pages/editor/sections/Hero.jsx
> +        <ShortTextField maxLength="60"label="Title" onChange={this.handleChange} value={this.props.data.title} name="title"/>
I haven't tested it, hence the "Once I can test this in local I will assign someone to review" in the pr description.

You are probably right, I read this from the react docs:
`In React, all DOM properties and attributes (including event handlers) should be camelCased. For example, the HTML attribute tabindex corresponds to the attribute tabIndex in React.`

https://facebook.github.io/react/docs/dom-elements.html

So next step (once I test it) is to find where the actual inputs are, and then add the `maxLength="__"` to that file? I can do that tonight. 🌃

2016-11-24 22:03 UTC, hwkr commented
Thoughts: maybe we want to pass down the max length as a React prop rather than hardcoding it for every field.

2016-11-24 22:24 UTC, kelseyll commented
If you think you could do that super quickly then I'm down. Honestly though, I don't think code optimization is really what we need to be focusing on right now (we have 7 days until presentation) 💯

2016-11-25 01:44 UTC, hwkr approved these changes

2016-11-25 01:45 UTC, hwkr commented
Okay, I'll just merge it then.

2016-11-25 01:45 UTC, merged